"""Init

Revision ID: 363d39709a5d
Revises: ce8e6552cb82
Create Date: 2023-04-01 22:26:46.986660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363d39709a5d'
down_revision = 'ce8e6552cb82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
