"""Init

Revision ID: 4f5ca4e02860
Revises: cfa5294f1553
Create Date: 2023-04-01 22:44:37.818228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5ca4e02860'
down_revision = 'cfa5294f1553'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
