"""Init

Revision ID: b6105c312a5f
Revises: d9f8b873196f
Create Date: 2023-04-01 22:16:50.171390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6105c312a5f'
down_revision = 'd9f8b873196f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
