"""Init

Revision ID: ce8e6552cb82
Revises: b6105c312a5f
Create Date: 2023-04-01 22:21:02.574882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8e6552cb82'
down_revision = 'b6105c312a5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
