"""Init

Revision ID: cfa5294f1553
Revises: ef23757fa1e0
Create Date: 2023-04-01 22:38:28.834283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa5294f1553'
down_revision = 'ef23757fa1e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
