"""Init

Revision ID: d9f8b873196f
Revises: d58bbe435a5b
Create Date: 2023-03-30 21:46:39.459910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f8b873196f'
down_revision = 'd58bbe435a5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
